import { ContactProfile, StatusBarConfig, ThemeConfig, WallpaperConfig, ChatMessage } from '../types/chat';

// Generated assets
export const ASSETS = {
  wallpaper: '/src/assets/images/romantic_roses_wallpaper_1790873686052.jpg',
  purpleMicBadge: '/src/assets/images/purple_neon_mic_badge_1790873697275.jpg',
  warningAvatarBadge: '/src/assets/images/warning_avatar_badge_1790873707562.jpg',
};

export const DEFAULT_RECIPIENT: ContactProfile = {
  name: 'ℬoss Sunny 😈',
  nameFont: 'cursive',
  avatarUrl: ASSETS.warningAvatarBadge,
  statusText: '',
  isOnline: false,
  isBusiness: true,
  isVerified: false,
  showCustomBadge: false,
};

export const DEFAULT_SENDER: ContactProfile = {
  name: 'You',
  nameFont: 'default',
  avatarUrl: ASSETS.purpleMicBadge,
  statusText: '',
  isOnline: true,
  isBusiness: false,
  isVerified: false,
};

export const DEFAULT_STATUS_BAR: StatusBarConfig = {
  showStatusBar: true,
  time: '5:32 PM',
  batteryLevel: 68,
  isCharging: false,
  wifiStrength: 4,
  signalStrength: 4,
  networkType: '4G',
  showAlarm: false,
  showLocation: false,
  showBluetooth: false,
  style: 'android',
  darkModeIcons: false, // white icons on dark background
};

export const THEMES: Record<string, ThemeConfig> = {
  reference_purple: {
    preset: 'reference_purple',
    name: 'Reference Velvet Purple (Screenshot)',
    isDarkMode: true,
    headerBg: '#0f0c15',
    chatBg: '#0b0910',
    incomingBubbleBg: '#23272a',
    incomingTextColor: '#e2e8f0',
    incomingTimeColor: '#94a3b8',
    outgoingBubbleBg: '#67207c',
    outgoingTextColor: '#ffffff',
    outgoingTimeColor: '#d8b4e2',
    inputBarBg: '#181520',
    inputTextColor: '#f8fafc',
    accentColor: '#9d32b5',
    fontFamily: 'cursive',
  },
  whatsapp_dark: {
    preset: 'whatsapp_dark',
    name: 'Official WhatsApp Dark Mode',
    isDarkMode: true,
    headerBg: '#1f2c34',
    chatBg: '#0b141a',
    incomingBubbleBg: '#202c33',
    incomingTextColor: '#e9edef',
    incomingTimeColor: '#8696a0',
    outgoingBubbleBg: '#005c4b',
    outgoingTextColor: '#e9edef',
    outgoingTimeColor: '#8696a0',
    inputBarBg: '#1f2c34',
    inputTextColor: '#e9edef',
    accentColor: '#00a884',
    fontFamily: 'roboto',
  },
  whatsapp_light: {
    preset: 'whatsapp_light',
    name: 'Official WhatsApp Light Mode',
    isDarkMode: false,
    headerBg: '#008069',
    chatBg: '#efeae2',
    incomingBubbleBg: '#ffffff',
    incomingTextColor: '#111b21',
    incomingTimeColor: '#667781',
    outgoingBubbleBg: '#d9fdd3',
    outgoingTextColor: '#111b21',
    outgoingTimeColor: '#667781',
    inputBarBg: '#ffffff',
    inputTextColor: '#111b21',
    accentColor: '#00a884',
    fontFamily: 'roboto',
  },
  amoled_black: {
    preset: 'amoled_black',
    name: 'AMOLED Midnight Black',
    isDarkMode: true,
    headerBg: '#000000',
    chatBg: '#000000',
    incomingBubbleBg: '#18181b',
    incomingTextColor: '#fafafa',
    incomingTimeColor: '#71717a',
    outgoingBubbleBg: '#27272a',
    outgoingTextColor: '#fafafa',
    outgoingTimeColor: '#a1a1aa',
    inputBarBg: '#09090b',
    inputTextColor: '#fafafa',
    accentColor: '#10b981',
    fontFamily: 'default',
  },
  whatsapp_business: {
    preset: 'whatsapp_business',
    name: 'WhatsApp Business Teal',
    isDarkMode: true,
    headerBg: '#0e2429',
    chatBg: '#0a171a',
    incomingBubbleBg: '#182b30',
    incomingTextColor: '#e8f3f5',
    incomingTimeColor: '#7da0a8',
    outgoingBubbleBg: '#0f5257',
    outgoingTextColor: '#ffffff',
    outgoingTimeColor: '#97d2d6',
    inputBarBg: '#14272c',
    inputTextColor: '#e8f3f5',
    accentColor: '#00a884',
    fontFamily: 'roboto',
  },
};

export const DEFAULT_WALLPAPER: WallpaperConfig = {
  type: 'image',
  imageUrl: ASSETS.wallpaper,
  opacity: 0.85,
  blur: 0,
  darkness: 0.35,
  zoom: 1,
};

// Exact messages from the uploaded reference screenshot
export const REFERENCE_MESSAGES: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'recipient',
    type: 'text',
    text: 'How e de be',
    time: '7:36 PM',
    status: 'none',
  },
  {
    id: 'msg-2',
    sender: 'user',
    type: 'voice_note',
    duration: '0:12',
    time: '7:37 PM',
    status: 'read',
    avatarBadgeType: 'purple_mic',
    avatarBadgeUrl: ASSETS.purpleMicBadge,
    waveformProgress: 18,
  },
  {
    id: 'msg-3',
    sender: 'recipient',
    type: 'text',
    text: 'E fit be',
    time: '7:38 PM',
    status: 'none',
  },
  {
    id: 'msg-4',
    sender: 'user',
    type: 'text',
    text: 'Yeah',
    time: '7:39 PM',
    status: 'read',
  },
  {
    id: 'msg-5',
    sender: 'recipient',
    type: 'voice_note',
    duration: '0:16',
    time: '7:52 PM',
    status: 'none',
    avatarBadgeType: 'warning_icon',
    avatarBadgeUrl: ASSETS.warningAvatarBadge,
    waveformProgress: 35,
  },
  {
    id: 'msg-6',
    sender: 'user',
    type: 'voice_note',
    duration: '0:07',
    time: '7:53 PM',
    status: 'read',
    avatarBadgeType: 'purple_mic',
    avatarBadgeUrl: ASSETS.purpleMicBadge,
    waveformProgress: 22,
  },
  {
    id: 'msg-7',
    sender: 'recipient',
    type: 'text',
    text: 'Alright',
    time: '7:53 PM',
    status: 'none',
  },
  {
    id: 'msg-8',
    sender: 'user',
    type: 'text',
    text: 'U still dey there',
    time: '9:04 PM',
    status: 'read',
  },
  {
    id: 'msg-9',
    sender: 'user',
    type: 'text',
    text: 'Nah this rain stop me',
    time: '9:04 PM',
    status: 'read',
  },
  {
    id: 'msg-10',
    sender: 'recipient',
    type: 'text',
    text: 'I don enter house',
    time: '9:04 PM',
    status: 'none',
  },
  {
    id: 'msg-11',
    sender: 'user',
    type: 'text',
    text: 'Okay',
    time: '9:08 PM',
    status: 'read',
  },
  {
    id: 'msg-12',
    sender: 'recipient',
    type: 'date_divider',
    text: 'Today',
    time: '',
  },
  {
    id: 'msg-13',
    sender: 'user',
    type: 'text',
    text: 'Happy new month',
    time: '4:32 PM',
    status: 'read',
  },
  {
    id: 'msg-14',
    sender: 'user',
    type: 'channel_invite',
    time: '5:32 PM',
    status: 'read',
    channelName: 'LEGIT 🤑 UPDATES ✅✅✅',
    subtitle: 'Channel admin invite',
    statusBadge: 'Invite accepted',
    description: "Accept this invitation to be an admin for my WhatsApp channel, 'LEGIT 🤑 UPDATES ✅✅✅'",
  },
];

export const OTHER_PRESETS = [
  {
    id: 'crypto_deal',
    title: 'Crypto Deal VIP',
    description: 'High-stake trade confirmation and wallet update',
    theme: 'amoled_black',
    recipient: {
      name: 'Satoshi Alpha 🚀',
      nameFont: 'default' as const,
      avatarUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=150&auto=format&fit=crop&q=80',
      statusText: 'Online',
      isOnline: true,
      isBusiness: false,
      isVerified: true,
    },
    messages: [
      {
        id: 'p1-1',
        sender: 'recipient' as const,
        type: 'text' as const,
        text: 'Did the 5.2 ETH transaction settle on L2 yet?',
        time: '11:42 AM',
        status: 'none' as const,
      },
      {
        id: 'p1-2',
        sender: 'user' as const,
        type: 'text' as const,
        text: 'Confirmed with 32 block confirmations ⚡',
        time: '11:43 AM',
        status: 'read' as const,
      },
      {
        id: 'p1-3',
        sender: 'user' as const,
        type: 'voice_note' as const,
        duration: '0:24',
        time: '11:44 AM',
        status: 'read' as const,
        waveformProgress: 40,
      },
      {
        id: 'p1-4',
        sender: 'recipient' as const,
        type: 'text' as const,
        text: 'Perfect! Signing the multisig now.',
        time: '11:45 AM',
        status: 'none' as const,
      },
    ],
  },
  {
    id: 'business_client',
    title: 'Creative Agency Client',
    description: 'Project approval and feedback discussion',
    theme: 'whatsapp_business',
    recipient: {
      name: 'Elena Rostova (Design Dir.)',
      nameFont: 'roboto' as const,
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      statusText: 'WhatsApp Business Account',
      isOnline: false,
      isBusiness: true,
      isVerified: true,
    },
    messages: [
      {
        id: 'b1-1',
        sender: 'recipient' as const,
        type: 'text' as const,
        text: 'Hi team, reviewed the latest Figma prototypes. The typography hierarchy looks impeccable!',
        time: '2:15 PM',
        status: 'none' as const,
      },
      {
        id: 'b1-2',
        sender: 'user' as const,
        type: 'text' as const,
        text: 'Thank you Elena! We adjusted the contrast ratios and touch padding per your feedback.',
        time: '2:18 PM',
        status: 'read' as const,
      },
      {
        id: 'b1-3',
        sender: 'recipient' as const,
        type: 'text' as const,
        text: 'Approved for final release! 🚀 Let us push to staging.',
        time: '2:20 PM',
        status: 'none' as const,
      },
    ],
  },
];
